# Generated by Django 4.2.5 on 2023-09-20 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_useraccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='user_id',
            new_name='username',
        ),
    ]
