# Generated by Django 4.2.5 on 2023-09-25 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_rename_user_id_useraccount_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
