# Generated by Django 4.2.5 on 2023-10-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_alter_textlibrary_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textlibrary',
            name='website_url',
            field=models.URLField(),
        ),
    ]
