# Generated by Django 4.2.5 on 2023-10-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_useraudios'),
    ]

    operations = [
        migrations.AddField(
            model_name='textlibrary',
            name='embedding',
            field=models.JSONField(null=True),
        ),
    ]
