# Generated by Django 4.2.5 on 2023-10-20 04:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0010_textlibrary_embedding'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TextLibrary',
            new_name='GlobalAudioLibrary',
        ),
    ]
